### ISSUE TITLE
not working in php7.1

### ISSUE THREAD

**Issue by haroon310** [andrewmriley/phpformmail#1]
hi, this does not work in php7.1 probably because of deprecated eregi() 
is there any alternative script with upgraded code? thanks

**Comment by andrewmriley** [comment]
Right now there isn't an upgraded version. I started a new branch ages ago with updates but never fixed it. Patches are always welcome.

**Comment by haroon310** [comment]
The error i am getting is:
Fatal error: Uncaught Error: Call to undefined function eregi() in (**path**)/formmail.php:106 Stack trace: #0 (**path**)/formmail.php(560): check_referer(Array) #1 {main} thrown in (**path**)/formmail.php on line 106

Do you think changing eregi to preg_match throughout the code would resolve the issue or there will be something else that is required. I tried changing to preg_match but have no idea about how to use the delimiters so could not experiment the change. 

Can you recommend an alternate that works in php7.1
thanks

**Comment by haroon310** [comment]
great work! but do i need to copy and paste all the new code into the old formmail.php to test? i cant find the new formmail.php (1.7.3) file.

**Comment by andrewmriley** [comment]
Yes, please copy the code from https://github.com/andrewmriley/phpformmail/blob/beta-1.7.3/formmail.php into your formmail.php.

**Comment by haroon310** [comment]
thanks, all good and working!

**Comment by andrewmriley** [comment]
This is now merged into master for all users to use. #2
