### ISSUE TITLE
Form don't send email for bcc email addresses

### ISSUE THREAD

**Issue by jawadulhassan-arshad** [andrewmriley/phpformmail#6]
It seems that if I am trying to add emails for bcc recipient the formmailer don't work.

I am getting recipient error message all the time.

**Comment by andrewmriley** [comment]
Can you please post the error message and the bcc related field from the html (but please obscure the email addresses.)

**Comment by jawadulhassan-arshad** [comment]
Hi Andrew 
The message was something like recipient address don't match or not in the allowed list. 
I ll send you screenshot in an hour. 

Sent from Yahoo Mail on Android 
 
  On Fri, 21 Feb 2020 at 18:24, Andrew M Riley<notifications@github.com> wrote:   
Can you please post the error message and the bcc related field from the html (but please obscure the email addresses.)

**Comment by jawadulhassan-arshad** [comment]
Hi Andrew
Please check the image in the attachment.
Regards
Jawad
    On Friday, February 21, 2020, 06:24:41 PM GMT+5, Andrew M Riley <notifications@github.com> wrote:  
 
 
Can you please post the error message and the bcc related field from the html (but please obscure the email addresses.)

**Comment by andrewmriley** [comment]
I see your posts but the attachment isn't attached.

**Comment by jawadulhassan-arshad** [comment]
Sorry I miss your email.

Actually if you add about 3 addresses in recipient array and 3 in bcc_recipient email address then the error will show.

This is error below.

https://drive.google.com/file/d/1VCa7LNbk0B-kXBIuM2aYyDvyc0bLHoPx/view?usp=sharing

Regards

Jawad

[Screen Shot 2020-02-17 at 3 41 38 PM]

(https://user-images.githubusercontent.com/6385034/75937229-21a0f480-5ea6-11ea-80cf-54650a9e0401.png)

**Comment by andrewmriley** [comment]
This type of error usually means your have a recipient (bcc_recipient in this case) who's domain isn't listed in your $referers inside of the formmail.php

From the docs:
<p> This array allows you to define the domains that you will allow forms to reside on and use your PHPFormMail script. If a user tries to put a form on another server, that is not in your list, they will receive an error message when someone tries to fill out their form. By placing boaddrink.com in the $referers array, this DOES NOT allow www.boaddrink.com, ftp.boaddrink.com, any other http address with boaddrink.com in it. I included boaddrink.com's IP address to access this script as well, just to be on the safe side. As of version 1.5.0 you can now use regular expressions in the $referers array.

Note: The domains listed in the $referers array must also include the domain that the e-mail is going to.

Example: If the recipient of the e-mail is test@example.com and the form is hosted on boaddrink.com, your $referers array will have to look like:

` $referers = array("boaddrink.com", "example.com");`

Remember, the domain name of the recipient's domain must be listed in the $referer array, even if the form isn't hosted on that domain. Rule of thumb, include the domain name that is hosting the form AND include the domain name of the recipients (This includes recipient, recipient_cc and recipient_bcc).

**Comment by andrewmriley** [comment]
Closing due to a month of non-reply.
